### PR TITLE
csv2mtbl: Handle long lines

### PR DESCRIPTION
**Pull request by TomSellers**
`buffio.Scanner` has a default token limit ([MaxScanTokenSize](https://godoc.org/bufio#pkg-constants)) of 65,535.  If a line exceeds this limit `buffio.Scanner` will generate an error and will break out of a `.Scan()` loop if one is in use. 

From the docs:

> [Scanning stops unrecoverably at EOF, the first I/O error, or a token too large to fit in the buffer](https://godoc.org/bufio#Scanner)

The calling code would need to check `scanner.Err()` in order to detect this event.

In the case of `inetdata-csv2mtbl` this means that the tool will cease ingesting data, write out any existing data, and exit with 0.  A user will not have any idea that the resulting `mtbl` file is incomplete unless they check the line counts of the source and destination files.

I observed this in the wild while testing against some Project Sonar DNS data that had 1,777,893,388 records. My finished `mtbl` file had 1,367,596,199 records.  This was due to the code trying to process a record for `s3-website-us-east-1.amazonaws.com` which was 79,314 characters long (mostly `A` records). The code immediately exited the `.Scan()` loop and continued on from there.

This PR increases the Scanner token limit to 98,304. This value was sort of arbitrary in that it was nearly 2,000 larger than the largest record size I've seen so far.  The PR also adds logic to detect if the error is triggered, notify the user, and exit with a non-0 exit code.

I have successfully processed all of the records in the dataset above after applying these changes.

**Testing**
File with the long record: https://gist.github.com/TomSellers/0529d71eb6599aa49f7dd5ac46125f86

The test command below uses a variation of `dump` tool built from here: https://github.com/hdm/golang-mtbl/blob/master/examples/dump.go

Command:
```shell
cat broken.txt | inetdata-csv2mtbl -M 2 -r -broken.mtbl &&  dump broken.mtbl | wc -l
```

A couple of questions:
1. Should the value for MaxScanTokenSize be bumped higher?
2. Should this value be tune-able at runtime?

### CODE REVIEW

**Comment by hdm** [comment]
Thanks Tom! We can bump this even further if needed

**Comment by hdm** [comment]
Re: runtime, only if someone is babysitting this to see the error I guess; I know the buffer limit impacts the processing speed, maybe have it increase the buffer length on error automatically, up to some sane limit (1Mb)?

**Comment by TomSellers** [comment]
You can't resize the value of MaxScanTokenSize after Scanning has started.  You have to create the scanner, adjust the buffer if needed, and start scanning.

https://godoc.org/bufio#Scanner.Buffer

You could potentially start up another scanner with a larger MaxScanTokenSize but I'm not sure what happened to the line the code just choked on.

**Comment by hdm** [comment]
Ah, good point. Maybe bumping this to 256k or so then?

**Comment by TomSellers** [comment]
That'd definitely provide breathing room and wouldn't be much memory compared to what this code is generally using (at least during my runs).

**Pull request merged**
